### ISSUE TITLE
Table 2 - citizen science as sampling event data

### ISSUE THREAD

**Issue by CecSve** [gbif/doc-freshwater-data-publishing-guide#12]
Some citizen science projects are standardized and could be considered sampling events. For example, in Denmark there is a [national multi-year citizen science program](https://forskning.snm.ku.dk/citizen-science/dnaogliv/) where high school students collect water samples to detect invasive and threatened species. The samples are processed in the lab by qPCR techniques by the high schoolers, but under supervision of NHM and university staff and with quality control incorporated. 

I would consider to put a X in the sampling event box or at least a (X), since it is a bit of a gray area and depending on the citizen science project, can be more or less advanced.

**Comment by dschigel** [comment]
This is an important highlight and the more we go ahead the more combos like freshwater x survey x eDNA we will see. The fact we produce separate guides help entrance from one's comfortable professional identity prospective "I am the freshwater guy - this guide is for me", proved by intro. As you read on, and esp. attempt data standartization and data publishing, many guides can become publisher's nightmare: let's open general GBIF guide on page 1, citizen science guide on page 3, freshwater on page 5, DNA on page 7. For one and very same dataset! I am painting grotesque future mainly for us in GBIFS to consider how guide(s) will evolve. In the context of new data model these issues should hopefully reduce or disappear.

**Comment by jenlento** [comment]
@CecSve Thank you for this excellent example. We do recognize that there's a distinction between an individual using iNaturalist, for example, where there won't be sampling event data, and an organized sampling event conducted by communities either in partnership with or following training from professionals. We made this distinction by including a separate class, which we termed community-based research. If you look at our definitions, what you described falls nicely under community-based research, which we did indicate could have sampling event data. Here is the definition for reference: Community-based research data: data that were collected through organized public participation in sampling events or public-led sampling events, designed and/or operated through collaboration with professionals. Expert training by professionals instills confidence in the accuracy of the data, but the potential for error is higher than for professional data.

We feel that having this separate category allows us to easily differentiate the citizen science data that came from an organized event with sampling event data from those that were observations without professional/technical guidance/support

**Comment by jenlento** [comment]
@dschigel We don't want to suggest that there needs to be a separate guide that you go to for citizen science if the data are freshwater in nature. Rather, we believe that the data should be tagged as citizen science, because this will allow the user to better understand how the data were collected and therefore what the limitations to using the data might be. This is in the interest of stronger metadata, but not intended to suggest that different guides must be used. The DNA is a separate guide, however, as we focused on non-DNA data.
