### ISSUE TITLE
Habitat use by freshwater organisms

### ISSUE THREAD

**Issue by CecSve** [gbif/doc-freshwater-data-publishing-guide#13]
Feedback for: https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#habitat-use

> There are several spatial scales at which habitat information should be reported with observation data to improve data utility and usability. Here, we define these based on definitions in the [IUCN Global Ecosystem Typology](https://global-ecosystems.org/page/typology), which is a hierarchical classification system that groups the world’s ecosystems by [realm](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#realm), [biome](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#biome), and [ecosystem functional groups](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#ecosystem-functional-group).

It could be made more clear how that data should be shared on GBIF. Currently you can publish habitat data in the [dwc:habitat](https://dwc.tdwg.org/terms/#dwc:habitat) field and there is no controlled vocabulary for this field. I can see the benefit of mentioning the IUCN Typology, but neither realm, biome or functional ecosystem are accepted terms in dwc (although see [this issue](https://github.com/tdwg/dwc/issues/38)) and are not supported by GBIF. Furthermore, habitat is not searchable for users, yet (but see [this issue](https://github.com/gbif/gbif-api/issues/131#issuecomment-2161461424)). 

I propose the guide includes the dwc:habitat field in the text:

> There are several spatial scales at which habitat information **([dwc:habitat](https://dwc.tdwg.org/terms/#dwc:habitat))** should be reported with observation data to improve data utility and usability. Here, we define these based on definitions in the [IUCN Global Ecosystem Typology](https://global-ecosystems.org/page/typology), which is a hierarchical classification system that groups the world’s ecosystems by [realm](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#realm), [biome](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#biome), and [ecosystem functional groups](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#ecosystem-functional-group).

but it should ideally also be specified how the IUCN category information should be published. Contact helpdesk@gbif.org know if you need help defining how such data could be published. Also, mention the [proposed terms](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/index.en.html#freshwater-dwc-extension-terms) that could be relevant.

A final remark, please also be aware that the ENVO vocabulary for environmental features are currently in use in [the DNA-derived publishing guide](https://docs.gbif.org/publishing-dna-derived-data/en/) and they do not correspond well to the IUCN categories (see this [comment](https://github.com/tdwg/dwc/issues/38#issuecomment-2164188793)). It is worth mentioning that the ENVO vocabulary exist whether or not you choose to adhere the the IUCN typology.

@ManonGros might be able to provide further insights

**Comment by jenlento** [comment]
@CecSve Thank you for the information about ENVO and links to ongoing discussions about including biome in the terms. We do indicate in the guide that the habitat terms should be entered in dynamicProperties, as indicated by this text in section 2.2:
"Other freshwater-specific habitat descriptions, including the biome, ecosystem functional group, lake zone and river mesohabitat can be entered in the dynamicProperties field, although the ultimate goal is to create a freshwater DwC extension in GBIF (see §3.1)."
However, we can more explicitly state that this is because these terms are not existing fields in DwC. @kcopas after the sentence that I pasted above, can you please include the sentence, "The use of dynamicProperties is necessary for these habitat descriptions because biome, ecosystem functional group, lake zone, and river mesohabitat are not currently accepted terms in DwC."

**Comment by jenlento** [comment]
@CecSve With respect to indicating the field in the text, we haven't done this with any other fields in the introduction, and this information is explained later in the guide. Therefore, we prefer not to mention it in this early section of the guide.

**Comment by jenlento** [comment]
Change made

**Comment by ManonGros** [comment]
**Decision:** promote using the habitat field (https://dwc.tdwg.org/terms/#dwc:habitat) rather than the dynamicProperties

**Comment by jenlento** [comment]
We have updated the text and tables to use the habitat field instead of dynamicProperties, as discussed.

**Comment by schmikloi** [comment]
Dear sender,

Thank you for your message. I am currently out of office and will return on November 4th. I apologise for any delay in my response and will get back to you as soon as possible upon my return.

Best regards,
Astrid
