### ISSUE TITLE
Sampling methods

### ISSUE THREAD

**Issue by CecSve** [gbif/doc-freshwater-data-publishing-guide#15]
Feedback for: https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#sampling-methods

> Sampling methods play a major role in determining how comparable different freshwater data are and whether freshwater data from different sources can be combined in a meaningful meta-analysis of biodiversity measures and community composition ([Lento et al. 2019](https://caff.is/freshwater); [Jarvis et al. 2023](https://doi.org/10.1111/fwb.14143)). For example, different freshwater fish sampling gear types are only effective on a portion of the fish [assemblage](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#assemblage), and some net mesh sizes fail to capture small-bodied fish species. Combining fish data with diverse sampling methods may thus introduce methodological bias into the meta-analysis.

I propose again to give concrete publishing term examples for users:

> Sampling methods **(which can be captured by [dwc:samplingProtocol](https://dwc.tdwg.org/terms/#dwc:samplingProtocol), [dwc:samplingEffort](https://dwc.tdwg.org/terms/#dwc:samplingEffort) and other related [Event terms](https://dwc.tdwg.org/terms/#event))** play a major role in determining how comparable different freshwater data are and whether freshwater data from different sources can be combined in a meaningful meta-analysis of biodiversity measures and community composition ([Lento et al. 2019](https://caff.is/freshwater); [Jarvis et al. 2023](https://doi.org/10.1111/fwb.14143)). For example, different freshwater fish sampling gear types are only effective on a portion of the fish [assemblage](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#assemblage), and some net mesh sizes fail to capture small-bodied fish species. Combining fish data with diverse sampling methods may thus introduce methodological bias into the meta-analysis.

Please also link to the proposed terms that could be useful in the [recommended terms](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/index.en.html#freshwater-dwc-extension-terms) to be included in DwC, and be clear what is currently possible vs. what is not currently possible to share.

@ManonGros may have further comments

**Comment by jenlento** [comment]
@CecSve As noted in earlier comments, we prefer not to provide the DwC terms at this point in the background information, as it will be confusing to readers who are not yet familiar with terms and their use. Later, we go through these terms with specific examples and recommendations as we describe how the user should set up their data, and we feel it is better for the reader to see this information in the context of the tables and descriptions provided below. This introductory section sets the stage for the detailed tables, as it introduces the reader to the concepts that will be critical when providing data to GBIF.
