### ISSUE TITLE
Publishing specific data categories on GBIF

### ISSUE THREAD

**Issue by CecSve** [gbif/doc-freshwater-data-publishing-guide#18]
Feedback for: https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#specific-categories

> An important part of publishing data on GBIF is ensuring that sufficient metadata are provided to allow future use of the published data. Resource metadata describe the details about the dataset itself, including the title, language, ownership, and usage rights. Metadata that describe the observations, such as the location and date, are included as part of the occurrence data. Extended metadata describing the sampling protocols, sample extent, and effort are provided within the sampling-event data.

I wonder if this paragraph could be made more clear. For example, time and location can also be captured on a dataset level (in the IPT you can infer that information based on the range of the coordinates and eventDates), so perhaps it should instead be:

 > An important part of publishing data on GBIF is ensuring that sufficient metadata are provided to allow future use of the published data. Some[ metadata is registered at the resource (dataset) level](https://ipt.gbif.org/manual/en/ipt/latest/resource-metadata#required-metadata-fields) (i.e. the dataset description, version, citation, rights, keywords, contacts, taxonomic and geographic scope) while other metadata can be captured in the records themselves in either [occurrence](https://ipt.gbif.org/manual/en/ipt/latest/occurrence-data#required-dwc-fields) or [sampling-event](https://ipt.gbif.org/manual/en/ipt/latest/sampling-event-data#required-dwc-fields) tables. 

Another comment:

> We recommend adding the type of observation (opportunistic observation data, targeted sampling data, or assemblage sampling data (see [§1.2.2](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#freshwater-categories))) and the type of data contribution (professional data, community-based monitoring data, or citizen science data) to the occurrence data.

It should be made clear that this is currently not possible in a dedicated field but a [proposal](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#freshwater-dwc-extension) is underway for a term to capture this information. Until then, the guid could propose to include such information in [dwc:occurrenceRemarks](https://dwc.tdwg.org/terms/#dwc:occurrenceRemarks), [dwc:eventRemarks](https://dwc.tdwg.org/terms/#dwc:eventRemarks) or [dwc:dynamicProperties](https://dwc.tdwg.org/terms/#dwc:dynamicProperties) - other ideas @ManonGros?

**Comment by jenlento** [comment]
Thank you for these suggestions. We have adjusted the text as suggested to more clearly describe the resources metadata. We have also added links to the sections that indicate how type of observation and type of data contribution should be added (sections 2.2 and 3.1.1)
