### ISSUE TITLE
Data preparation and standards

### ISSUE THREAD

**Issue by CecSve** [gbif/doc-freshwater-data-publishing-guide#22]
Feedback for: https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#data-prep-and-standards

> GBIF therefore recommends that users provide as much information as possible about higher classifications. Identification qualifiers (such as "cf."), working names, and common names should not be included in the [scientificName](https://rs.tdwg.org/dwc/terms/scientificName) field, as these will not align with the taxonomic backbone

Could be elaborated a bit:

> GBIF therefore recommends that users provide as much information as possible about higher classifications. Identification qualifiers (such as "cf."), working names, and common names should not be included in the [scientificName](https://rs.tdwg.org/dwc/terms/scientificName) field, as these will not align with the taxonomic backbone **and should instead be captured in the [dwc:identificationQualifier](https://dwc.tdwg.org/terms/#dwc:identificationQualifier) field.** 

@ManonGros this is only relevant for checklists right? If so, then it should be specified that it only makes sense to include for checklists.

It might make sense to link to[ the species matching tool](https://www.gbif.org/tools/species-lookup) in this paragraph, which publishers can use to match the names they plan to publish and get higher taxonomy and other checks of their data.

**Comment by jenlento** [comment]
Thank you for the comments. Changes made.
