### ISSUE TITLE
Occurrence datasets

### ISSUE THREAD

**Issue by CecSve** [gbif/doc-freshwater-data-publishing-guide#24]
Feedback for: https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#occurrence-datasets

> Occurrence data provide information about observations of taxa and the locations where they were found ([Table 5](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#table-05)). Although only coarse location information is required, the recommended best practice is to always provide coordinates (latitude and [longitude](https://dwc.tdwg.org/terms/#dwc:decimalLongitude) in decimal degrees), a geodetic datum, and a measure of the uncertainty around the coordinates (estimated precision).

For clarity, even though it is in the table below, I would add hyperlinks for the relevant terms in the text, like this:

> Occurrence data provide information about observations of taxa and the locations where they were found ([Table 5](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#table-05)). Although only coarse location information is required, the recommended best practice is to always provide coordinates ([**latitude](https://dwc.tdwg.org/terms/#dwc:decimalLatitude)** and **[longitude](https://dwc.tdwg.org/terms/#dwc:decimalLongitude**) in decimal degrees), a **[geodetic datum](https://dwc.tdwg.org/terms/#dwc:geodeticDatum) which will automatically be interpreted to WGS84 when data is published to GBIF**, and a measure of the **[uncertainty around the coordinates](https://dwc.tdwg.org/terms/#dwc:coordinateUncertaintyInMeters)**.

@ManonGros may have further comments

**Comment by jenlento** [comment]
Change made
