### ISSUE TITLE
Specific requirements for publishing freshwater data (freshwater amendments)

### ISSUE THREAD

**Issue by CecSve** [gbif/doc-freshwater-data-publishing-guide#26]
Feedback for: https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#table-07

Please be aware that both [sex](https://registry.gbif.org/vocabulary/Sex) (this version is to be implemented this year and is slightly different from the current version) and [lifeStage](https://registry.gbif.org/vocabulary/LifeStage) (in use, needs to be updated and inputs are welcome from the freshwater community for concept additions!) is interpreted by controlled vocabularies in GBIF.

**Comment by ManonGros** [comment]
Additional feedback: as far as I am aware all the measurement-related data cannot be shared in an event core file but rather in one of the measurementsOrFacts extensions available: https://rs.gbif.org/extension/measurements_or_facts_2024-02-19.xml or https://rs.gbif.org/extension/measurements_or_facts_2024-02-19.xml

**Comment by dschigel** [comment]
The discussions with the authors and the focus has been put on the terms and their correct use, less so on the cores, stars, extensions and other GBIF-specific data packaging peculiarities, which, as we know, will change. At the same time, not addressing data packing at all will make the guide not useable practically for data publishing (criticism we got for the DNA guide). Perhaps a practical solution is to have a hard (slowly changing or not changing at all) part with terms and advice on their use (agnostic of packaging), and soft part with practical advice on data publishing _today_ (and standing ready to re-write this soft part fast). That last part can be outside the freshwater guide altogether (but linked), as long as basic data publishing guidelines are satisfactory.

**Comment by jenlento** [comment]
We have updated sex based on the existing controlled vocabulary to include indeterminate, as that will be a useful term for freshwater. Lifestage was edited as per an earlier comment.

As far as where fields such as measurements should go, that is something that we must leave to GBIF to decide. The purpose of Table 7 is to indicate the information that should be provided for freshwater to maximize the utility of the data. The particulars of where those fields should go in GBIF is outside of our expertise and we look to you for guidance on what will work with the GBIF system. Would the measurement extension not be part of the event data? Our understanding is that occurrence dataset is for the biotic part of the observation while the event data provides the supporting information, including methods and environmental measurements. We are not clear on what, if any, changes are necessary to the text.

**Comment by jenlento** [comment]
Leaving open for feedback

**Comment by ManonGros** [comment]
**Decision**: change event to Extended Measurements or Facts extension: https://rs.gbif.org/extension/obis/extended_measurement_or_fact_2023-08-28.xml

**Comment by CecSve** [comment]
**Decision**: @CecSve to go through required list and check with EML

**Comment by jenlento** [comment]
We have updated the text and tables to now recommend fields in existing extensions. In addition, we have reframed section 3.1 and 3.1.1 to no longer talk about a proposed freshwater extension. Instead, this section speaks to the shortcomings of currently existing fields and indicates where we'd like to see new dedicated fields that could address these shortcomings.

**Comment by CecSve** [comment]
please be aware that the table currently lists dynamicProperties as required, but the examples include information about sampling approach which should rather be captured in the [samplingProtocol](https://dwc.tdwg.org/terms/#dwc:samplingProtocol) field. I suggest to include samplingProtocol in the table and make this required instead.

dynamicProperties could be 'share if available' or 'recommended'

**Comment by CecSve** [comment]
@dschigel we will transition recommendation status to only three levels:

- Required
- Recommended
- Share if available

You may want to adopt a similar approach, if possible, in the guides. However, you can choose to have another status structure. It just have to be clear that the requirements and recommendations are guide specific and not 'required' does not mean technically 'required'

**Comment by CecSve** [comment]
institutionCode should be recommended or strongly recommended and not required. As a data aggregator, we will have freshwater datasets/occurrences that are not necessarily coming from an institution.

**Comment by jenlento** [comment]
> please be aware that the table currently lists dynamicProperties as required, but the examples include information about sampling approach which should rather be captured in the [samplingProtocol](https://dwc.tdwg.org/terms/#dwc:samplingProtocol) field. I suggest to include samplingProtocol in the table and make this required instead.
> 
> dynamicProperties could be 'share if available' or 'recommended'

Changed dynamicProperties to be recommended. We did take the sampling approach information out and move it to a different term.

**Comment by jenlento** [comment]
> institutionCode should be recommended or strongly recommended and not required. As a data aggregator, we will have freshwater datasets/occurrences that are not necessarily coming from an institution.

Change made

**Comment by jenlento** [comment]
> [@dschigel](https://github.com/dschigel) we will transition recommendation status to only three levels:
> 
> * Required
> * Recommended
> * Share if available
> 
> You may want to adopt a similar approach, if possible, in the guides. However, you can choose to have another status structure. It just have to be clear that the requirements and recommendations are guide specific and not 'required' does not mean technically 'required'

Changed throughout to be one of these three options. But in Table 07, which is  a list of recommendations for adding to freshwater, we have Share if relevant instead of share if available, because this makes it more clear that it's only relevant for some organism groups.
