### ISSUE TITLE
minimum/maximumElevationInMeters

### ISSUE THREAD

**Issue by MattBlissett** [gbif/doc-freshwater-data-publishing-guide#28]
https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/index.en.html#table-07

> If sampling was done at one altitude only (e.g. no range), enter the actual altitude at which your sample was taken and leave maximumElevationInMeters blank.

I don't agree with this advice; if the altitude is known then the two fields should be identical (or within the precision of the instrument used to determine the altitude).

A minimum without a maximum is "from this altitude and up".

Similarly for the depth.

**Comment by jenlento** [comment]
Change made. Thank you for the correction.
