### ISSUE TITLE
identification​Verification​Status

### ISSUE THREAD

**Issue by MattBlissett** [gbif/doc-freshwater-data-publishing-guide#29]
> Use "1" for a verification through a renown expert and "0" for an unverified taxon.

I can't find the vocabulary that defines `1` as verification by a renowned expert.

As it's a recommended field we should link to one.  https://hiscom.github.io/hispid/vocabulary/identification_verification_status.xml uses words, and page 42 of https://www.bgbm.org/tdwg/acc/hispid30draft.doc uses numbers:

```
Content of Field			Meaning

	0	The name of the record has not been checked by any authority
	1	The name of the record determined by comparison with other named plants
	2	The name of the record determined by a taxonomist or by other competent persons using herbarium and/or library and/or documented living material
	3	The name of the plant determined by taxonomist engaged in systematic revision of the group
	4	The record is part of type gathering or propagated from type material by asexual methods
```

We don't currently index the field, but I think it's likely we'd choose to present data using words rather than opaque integers.

**Comment by DeboraArlt** [comment]
Words will be more informative. Integers need additional information to be able to know what the numbers stand for.
In the Swedish citizen science dataset Artportalen https://www.gbif.org/dataset/38b4c89f-584c-41bb-bd8f-cd1def33e92f a quite complex set of values is used: https://github.com/biodiversitydata-se/SOS/blob/master/Docs/Vocabularies.md#verificationstatus

**Comment by jenlento** [comment]
As this has not yet been indexed, we have suggested the use of the terms "verified", "unverified", and "requires verification" for now. This can be edited when the terms are indexed.
