### ISSUE TITLE
Humboldt Inventory event extention

### ISSUE THREAD

**Issue by DeboraArlt** [gbif/doc-freshwater-data-publishing-guide#32]
I do not understand why the guid not refers to any of the available extensions that would appear useful additions when publishing freshwater data.

For example, I would suggest to have a look at the new [Humboldt Inventory event extension](https://www.tdwg.org/community/osr/humboldt-extension/) that was created to support proper capture of key information about inventories. I am not sure whether the working group included freshwater people but I would think that the group used a broad approach to inventories. I suspect the Humboldt extension to be a quite useful extension for freshwater data, with the guide's scope clearly on monitoring data (data from inventories).

Similarly, reference to a other extensions would be useful, e.g. extendedMeasurementsOrFacts, or those relevant for DNA derived data.

**Comment by jenlento** [comment]
We reviewed the Humboldt Inventory event extension, but struggled to find terms that matched with our suggestions for freshwaters. In some cases, terms were similar to our suggestions, but just different enough to make them not interchangeable. For example, the Humboldt extension includes ecoiri:protocolNames, which provides the names of methods and approaches, whereas we have suggested samplingEquipment to provide the specific sampler and mesh size used. In this case, the equipment itself speaks to comparability of the data and is therefore necessary information.

To allow the users to determine if some of the fields in these extensions will be relevant to them, we have added text linking to these extensions and indicating that additional fields can be found there.
