### ISSUE TITLE
recordedByID and identifiedByID

### ISSUE THREAD

**Issue by ymgan** [gbif/doc-freshwater-data-publishing-guide#33]
Feedback on Table 7 of https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#freshwater-amendments

Please consider including the ID terms for `recordedBy` and `identifiedBy`:

- [recordedByID](http://rs.tdwg.org/dwc/terms/recordedByID)
- [identifiedByID](https://dwc.tdwg.org/terms/#dwc:identifiedByID)

Reasoning:

There are many ways to spell a name and there are also names that are common. Having an identifier (e.g. ORCID) will help to unambiguously identify the right person. It is also helpful for initiative like [Bionomia](https://bionomia.net/).

**Comment by jenlento** [comment]
Thank you for the suggestion. Change made.
