### ISSUE TITLE
Table column headers and table formatting

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-freshwater-data-publishing-guide#7]
> on the headline we had suggested "freshwater term definition", "freshwater example" etc.

We do not have the space to repeat freshwater 3-4 times in each column heading and make table spacing, width and alignment anything like pixel perfect. But we're in a guide to publishing freshwater data. The captions clearly indicate the focus of each table. The repetition of freshwater is unworkable in the design and editorially unnecessary, especially given that AsciiDoctor adjusts tables based on the content present, making any declared values more like guidelines than instructions.

Please let me know if there are specific rows or columns you'd like us to look at, but the general condition is about as good as it gets.

**Comment by jenlento** [comment]
I think that's fine. We were concerned about making sure it was very clear that these were recommendations for freshwater, but I agree that it should already be clear enough.

**Comment by schmikloi** [comment]
I am also fine; checked all the headlines and captions again:
Table 4: all words in the heading should be in capital letters
Table 5: should be "Example(s)"
Table 6: should be "Example(s)"
Table 7: should be "Example(s)"
