### ISSUE TITLE
Square brackets vs. parentheses in tables

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-freshwater-data-publishing-guide#8]
> in the column example we had further explanations in [] (square brackets): these are sometimes implemented in the table and sometimes replaced by ()

**Comment by kcopas** [comment]
Extensive use of square brackets in AsciiDoctor (the markup language used to format our documentation) is extremely problematic, as it relies on these characters for links. The intention is to replace brackets with parentheses. If any brackets remain, it simply means I've missed them.

**Comment by jenlento** [comment]
I think this is fine, particularly as the examples are shaded and the text that was in brackets is not shaded.

**Comment by schmikloi** [comment]
I agree, but checking this I saw that f. ex. "Adicella cremisa" in Table 4 "scientificName" is not shaded; I also found these non-shaded ones in other places. Is there any "rule" for the shades?

**Comment by kcopas** [comment]
@MattBlissett can you help me sort out what seems like an inconsistent display of `code-formatted text` both with and without shading?
* [with](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#table-05): line 3, column 3, "`Adicella cremisa Malicky, 1972`"
* [without](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#table-04): line 2, column 3, "`Adicella cremisa Malicky, 1972`"

I can't see any different in the source…

**Comment by MattBlissett** [comment]
There's a rule that `code text format` gets the background unless it's the only content in a table cell, but the rule defining what "only content" means is inadequate.

I've disabled it (see commit) for this document.
